/*
 * CardBridge Java Connector
 * OpenAPI Specifications for the CardBridge Intent Ticket Management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.intentticket;

import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;
import com.dcscc.connector.client.intentticket.api.IntentTicketRestApi;
import com.dcscc.connector.client.intentticket.model.CreateIntentTicketRequest;
import com.dcscc.connector.client.intentticket.model.IntentTicketResponse;

/** API examples for IntentTicketApi */
public class CreateIntentTicketExample {
    private volatile IntentTicketRestApi api;

    public IntentTicketRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("apiKey");
                    clientConfiguration.setSecretKey("secretKey");
                    clientConfiguration.setBaseUrl("https://api.thedecard.com");
                    api = new IntentTicketRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Create Intent Ticket
     *
     * <p>Creates a new intent ticket for managing business processes that require documentation, 
     * approval, or multi-step workflows. The ticket serves as a container for related documents, 
     * status tracking, and process management.
     * Weight: 5
     *
     * @throws ApiException if the Api call fails
     */
    public void createIntentTicketExample() throws ApiException {
        CreateIntentTicketRequest request = new CreateIntentTicketRequest();
        request.setTicketRef("ticket_ref_123");
        request.setTicketType("CREATE_CARD_EDD");
        request.setBusinessType("CARD_ORDER_ID");
        request.setBusinessId("card_order_456");
        
        // Complete EDD Source of Wealth - Salary example
        CreateIntentTicketRequest.EddSowSalary eddSowSalary = new CreateIntentTicketRequest.EddSowSalary();
        eddSowSalary.setEmployerName("Example Corp");
        eddSowSalary.setJobTitle("Software Engineer");
        eddSowSalary.setAnnualIncome("75000");
        
        // Add document URLs
        java.util.List<com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest> salaryDocs = 
            new java.util.ArrayList<>();
        com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest salaryDoc = 
            new com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest();
        salaryDoc.setFileName("salary_certificate.pdf");
        salaryDoc.setFilePath("/documents/salary_certificate.pdf");
        salaryDocs.add(salaryDoc);
        eddSowSalary.setDocUrls(salaryDocs);
        request.setEddSowSalary(eddSowSalary);
        
        // Complete EDD Source of Wealth - Business Revenue example
        CreateIntentTicketRequest.EddSowBizRevenue eddSowBizRevenue = new CreateIntentTicketRequest.EddSowBizRevenue();
        eddSowBizRevenue.setBusinessName("Tech Solutions LLC");
        eddSowBizRevenue.setNatureOfBusiness("Software Development");
        eddSowBizRevenue.setAnnualRevenue("500000");
        
        java.util.List<com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest> bizDocs = 
            new java.util.ArrayList<>();
        com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest bizDoc = 
            new com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest();
        bizDoc.setFileName("business_registration.pdf");
        bizDoc.setFilePath("/documents/business_registration.pdf");
        bizDocs.add(bizDoc);
        eddSowBizRevenue.setDocUrls(bizDocs);
        request.setEddSowBizRevenue(eddSowBizRevenue);
        
        ApiResponse<IntentTicketResponse> response = getApi().createIntentTicket(request);
    }

    /**
     * Create Intent Ticket for Increase Limit EDD
     *
     * <p>Demonstrates creating an intent ticket for limit increase with source of funds information.
     * Weight: 5
     *
     * @throws ApiException if the Api call fails
     */
    public void createIncreaseLimitEddTicketExample() throws ApiException {
        CreateIntentTicketRequest request = new CreateIntentTicketRequest();
        request.setTicketRef("limit_increase_ref_789");
        request.setTicketType("INCREASE_LIMIT_EDD");
        request.setBusinessType("CARD_ID");
        request.setBusinessId("card_789012");
        
        // EDD Source of Funds - Crypto example
        CreateIntentTicketRequest.EddSofCrypto eddSofCrypto = new CreateIntentTicketRequest.EddSofCrypto();
        eddSofCrypto.setPlatform("Binance");
        eddSofCrypto.setHoldingType("CUSTODIAN");
        
        java.util.List<com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest> cryptoDocs = 
            new java.util.ArrayList<>();
        com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest cryptoDoc = 
            new com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest();
        cryptoDoc.setFileName("crypto_statement.pdf");
        cryptoDoc.setFilePath("/documents/crypto_statement.pdf");
        cryptoDocs.add(cryptoDoc);
        eddSofCrypto.setDocUrls(cryptoDocs);
        request.setEddSofCrypto(eddSofCrypto);
        
        // EDD Source of Funds - Investment example
        CreateIntentTicketRequest.EddSofInvest eddSofInvest = new CreateIntentTicketRequest.EddSofInvest();
        eddSofInvest.setTypeOfInvestment("Stock Portfolio");
        eddSofInvest.setApproximateValue("250000");
        
        java.util.List<com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest> investDocs = 
            new java.util.ArrayList<>();
        com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest investDoc = 
            new com.dcscc.connector.client.intentticket.model.IntentTicketFileRequest();
        investDoc.setFileName("investment_portfolio.pdf");
        investDoc.setFilePath("/documents/investment_portfolio.pdf");
        investDocs.add(investDoc);
        eddSofInvest.setDocUrls(investDocs);
        request.setEddSofInvest(eddSofInvest);
        
        ApiResponse<IntentTicketResponse> response = getApi().createIntentTicket(request);
        System.out.println(response.getData());

    }
}
