/*
 * CardBridge Java Connector
 * OpenAPI Specifications for the CardBridge Intent Ticket Management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.intentticket;

import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;
import com.dcscc.connector.client.intentticket.api.IntentTicketRestApi;
import com.dcscc.connector.client.intentticket.model.BusinessType;
import com.dcscc.connector.client.intentticket.model.GeneratePreUploadUrlRequest;
import com.dcscc.connector.client.intentticket.model.PreUploadUrlResponse;

import java.util.Arrays;

/** API examples for IntentTicketApi */
public class GeneratePreUploadUrlExample {
    private volatile IntentTicketRestApi api;

    public IntentTicketRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("apiKey");
                    clientConfiguration.setSecretKey("secretKey");
                    clientConfiguration.setBaseUrl("https://api.cardbridge.com");
                    api = new IntentTicketRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Generate Pre-Upload URL
     *
     * <p>Generates secure pre-signed URLs for uploading documents related to intent tickets. 
     * This endpoint allows clients to upload files directly to secure storage without exposing 
     * sensitive credentials. The generated URLs have a limited validity period.
     * Weight: 2
     *
     * @throws ApiException if the Api call fails
     */
    public void generatePreUploadUrlExample() throws ApiException {
        GeneratePreUploadUrlRequest request = new GeneratePreUploadUrlRequest();
        request.setFileNames(Arrays.asList("passport.pdf", "utility_bill.pdf"));
        request.setBusinessType(BusinessType.CREATE_CARD_EDD);
        
        ApiResponse<PreUploadUrlResponse> response = getApi().generatePreUploadUrl(request);
        System.out.println(response.getData());

    }
}
