/*
 * CardBridge Java Connector
 * OpenAPI Specifications for the CardBridge Intent Ticket Management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.intentticket;

import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;
import com.dcscc.connector.client.intentticket.api.IntentTicketRestApi;
import com.dcscc.connector.client.intentticket.model.IntentTicketResponse;

/**
 * API examples for IntentTicketApi
 */
public class GetIntentTicketDetailExample {
    private volatile IntentTicketRestApi api;

    public IntentTicketRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("1B25F0E6D8724E229762C0FF9A864740");
                    clientConfiguration.setSecretKey("Gv5lSyHTuOrW1qYAyGWJdQCrFXxLoGUdYLdfFQ/oC/s=");
                    clientConfiguration.setBaseUrl("https://api.uatdcd.com");
                    api = new IntentTicketRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Get Intent Ticket Detail
     *
     * <p>Retrieves detailed information about a specific intent ticket, including its current status,
     * associated documents, and processing history. This endpoint supports querying by either ticket ID
     * or ticket reference.
     * Weight: 1
     *
     * @throws ApiException if the Api call fails
     */
    public void getIntentTicketDetailExample() throws ApiException {
        String ticketId = "4636702839222061312";
        String ticketRef = null; // Optional: can use ticket reference instead

        ApiResponse<IntentTicketResponse> response = getApi().getIntentTicketDetail(ticketId, ticketRef);
        System.out.println(response.getData());
    }
}
