/*
 * CardBridge Java Connector
 * Enterprise Management REST API Examples
 *
 * The version of the CardBridge API: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.enterprise;

import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;
import com.dcscc.connector.client.enterprise.api.EnterpriseRestApi;
import com.dcscc.connector.client.enterprise.model.BalanceResponse;

/**
 * API examples for Enterprise Balance Management
 */
public class GetEnterpriseBalanceExample {
    private EnterpriseRestApi api;

    public EnterpriseRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("your-api-key");
                    clientConfiguration.setSecretKey("your-secret-key");
                    clientConfiguration.setBaseUrl("https://api.thedecard.com");
                    api = new EnterpriseRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Get enterprise account balance
     *
     * <p>Retrieves the enterprise account balance for a specific currency.
     * The balance includes available funds, reserved amounts, and other financial details.
     * Weight: 1
     *
     * @throws ApiException if the Api call fails
     */
    public void getEnterpriseBalanceExample() throws ApiException {
        String currency = "978"; // ISO 4217 numeric currency code (EUR)
        ApiResponse<BalanceResponse> response = getApi().getEnterpriseBalance(currency);
        System.out.println(response.getData());
    }
}
