/*
 * CardBridge Java Connector
 * Enterprise Management REST API Examples
 *
 * The version of the CardBridge API: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.enterprise;

import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;
import com.dcscc.connector.client.enterprise.api.EnterpriseRestApi;
import com.dcscc.connector.client.enterprise.model.SettlementFileType;

/**
 * API examples for Enterprise Settlement File Management
 */
public class GetSettlementFileUrlExample {
    private EnterpriseRestApi api;

    public EnterpriseRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("your-api-key");
                    clientConfiguration.setSecretKey("your-secret-key");
                    clientConfiguration.setBaseUrl("https://api.thedecard.com");
                    api = new EnterpriseRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Get settlement file download URL
     *
     * <p>Generates a time-limited, secure URL for downloading settlement files
     * such as transaction reports, reconciliation files, and financial statements.
     * The URL expires after a certain period for security purposes.
     * Weight: 1
     *
     * @throws ApiException if the Api call fails
     */
    public void getSettlementFileUrlExample() throws ApiException {
        //  Using enum (recommended for type safety)
        String fileDate = "20240815"; // Date in YYYYMMDD format
        SettlementFileType fileTypeEnum = SettlementFileType.TRANSACTION;
        ApiResponse<String> response2 = getApi().getSettlementFileUrl(fileTypeEnum, fileDate);
        System.out.println("URL from enum method: " + response2.getData());
    }
}
