/*
 * CardBridge Java Connector
 * OpenAPI Specifications for the CardBridge Card Order Management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.card;

import com.dcscc.connector.client.card.api.CardOrderRestApi;
import com.dcscc.connector.client.card.model.CardOrderResponse;
import com.dcscc.connector.client.card.model.CreateCardOrderRequest;
import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;

/**
 * API examples for CardOrderApi
 */
public class CreateVirtualCardOrderExample {
    private volatile CardOrderRestApi api;

    public CardOrderRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("apiKey");
                    clientConfiguration.setSecretKey("secretKey");
                    clientConfiguration.setBaseUrl("https://api.thedecard.com");
                    api = new CardOrderRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Create Virtual Card Order
     *
     * <p>Creates a new virtual card order with customer and KYC information.
     * The virtual card will be issued instantly upon successful order processing and KYC verification.
     * Weight: 10
     *
     * @throws ApiException if the Api call fails
     */
    public void createVirtualCardOrderExample() {
        CreateCardOrderRequest request = new CreateCardOrderRequest();
        request.setProfileId("profile_123");
        request.setCardOrderRef("order_ref_456");

        // Complete CustomerInfo with all required fields
        CreateCardOrderRequest.CustomerInfo customerInfo = new CreateCardOrderRequest.CustomerInfo();
        customerInfo.setPhoneCountryCode("US");
        customerInfo.setPhone("+1234567890");
        customerInfo.setEmail("john.doe@example.com");
        customerInfo.setCustomerRef("customer_ref_123");
        request.setCustomerInfo(customerInfo);

        // Complete KycInfo with all required fields
        CreateCardOrderRequest.KycInfo kycInfo = new CreateCardOrderRequest.KycInfo();
        kycInfo.setSumsubShareToken("sumsub_token_abc123");
        kycInfo.setPoaDocType("UTILITY_BILL");
        kycInfo.setPoaDocUrlList(java.util.Arrays.asList("https://example.com/utility_bill.pdf"));
        kycInfo.setPoaDocDate("2024-01-15");
        kycInfo.setAddressLine1("123 Main Street");
        kycInfo.setAddressLine2("Apt 4B");
        kycInfo.setState("California");
        kycInfo.setCity("San Francisco");
        kycInfo.setPostalCode("94102");
        kycInfo.setCountry("US");
        kycInfo.setEmploymentStatus("EMPLOYED");
        kycInfo.setEmployerName("Tech Corp Inc");
        kycInfo.setEmploymentJobIndustry("INFORMATION_AND_COMMUNICATIONS");
        kycInfo.setOccupation("SOFTWARE_ENGINEER");
        kycInfo.setJobSeniority("MID_LEVEL");
        kycInfo.setPurposeOfAccount("DAILY_SPENDING");
        kycInfo.setSourceOfFunds("OWN_BANK_ACCOUNT");
        kycInfo.setSourceOfFundsCountry("US");
        kycInfo.setSourceOfWealth("EMPLOYMENT");
        request.setKycInfo(kycInfo);

        ApiResponse<CardOrderResponse> response = getApi().createVirtualCardOrder(request);
        System.out.println(response.getData());

    }

    /**
     * Create Virtual Card Order with Encrypted Fields
     *
     * <p>Demonstrates how to use encrypted customerInfo and kycInfo fields
     * for enhanced security when transmitting sensitive data.
     * Weight: 10
     *
     * @throws ApiException if the Api call fails
     */
    public void createVirtualCardOrderWithEncryptionExample() throws ApiException {
        CreateCardOrderRequest request = new CreateCardOrderRequest();
        request.setProfileId("profile_123");
        request.setCardOrderRef("order_ref_encrypted_456");
        
        // Generate IV for encryption
        String iv = com.dcscc.connector.client.common.utils.AESUtil.generateIV();
        String secretKey = "your-secret-key-here";
        
        // Create CustomerInfo object and encrypt it
        CreateCardOrderRequest.CustomerInfo customerInfo = new CreateCardOrderRequest.CustomerInfo();
        customerInfo.setPhoneCountryCode("US");
        customerInfo.setPhone("+1234567890");
        customerInfo.setEmail("john.doe@example.com");
        customerInfo.setCustomerRef("customer_ref_123");
        
        String customerInfoJson = com.google.gson.JsonParser.parseString(
            new com.google.gson.Gson().toJson(customerInfo)).toString();
        String encryptedCustomerInfo = com.dcscc.connector.client.common.utils.AESUtil.encryptGCM(
            customerInfoJson, secretKey, iv);
        
        // Create KycInfo object and encrypt it
        CreateCardOrderRequest.KycInfo kycInfo = new CreateCardOrderRequest.KycInfo();
        kycInfo.setSumsubShareToken("sumsub_token_abc123");
        kycInfo.setPoaDocType("UTILITY_BILL");
        kycInfo.setEmploymentStatus("EMPLOYED");
        kycInfo.setEmployerName("Tech Corp Inc");
        kycInfo.setSourceOfFunds("OWN_BANK_ACCOUNT");
        kycInfo.setSourceOfWealth("EMPLOYMENT");
        
        String kycInfoJson = com.google.gson.JsonParser.parseString(
            new com.google.gson.Gson().toJson(kycInfo)).toString();
        String encryptedKycInfo = com.dcscc.connector.client.common.utils.AESUtil.encryptGCM(
            kycInfoJson, secretKey, iv);
        
        // Set encrypted fields
        request.setEncryptionIV(iv);
        request.setCustomerInfoEncryption(encryptedCustomerInfo);
        request.setKycInfoEncryption(encryptedKycInfo);

        ApiResponse<CardOrderResponse> response = getApi().createVirtualCardOrder(request);
        System.out.println(response.getData());

    }
}
