/*
 * CardBridge Java Connector
 * OpenAPI Specifications for the CardBridge Card Order Management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.card;

import com.dcscc.connector.client.card.api.CardOrderRestApi;
import com.dcscc.connector.client.card.model.CardOrderResponse;
import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;

/**
 * API examples for CardOrderApi
 */
public class GetCardOrderDetailExample {
    private volatile CardOrderRestApi api;

    public CardOrderRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("apiKey");
                    clientConfiguration.setSecretKey("secretKey");
                    clientConfiguration.setBaseUrl("https://api.thedecard.com");
                    api = new CardOrderRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Get Card Order Detail
     *
     * <p>Retrieves detailed information about a card order using either the order ID or the order reference.
     * At least one of these parameters must be provided.
     * Weight: 1
     *
     * @throws ApiException if the Api call fails
     */
    public void getCardOrderDetailExample() throws ApiException {
        String cardOrderId = "order_123456";
        String cardOrderRef = "ref_789012";

        ApiResponse<CardOrderResponse> response = getApi().getCardOrderDetail(cardOrderId, cardOrderRef);
        System.out.println(response.getData());

    }
}
