/*
 * CardBridge Java Connector
 * OpenAPI Specifications for the CardBridge Card Order Management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.card;

import com.dcscc.connector.client.card.api.CardOrderRestApi;
import com.dcscc.connector.client.card.model.CardOrderResponse;
import com.dcscc.connector.client.card.model.ReplaceCardOrderRequest;
import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;

/**
 * API examples for CardOrderApi
 */
public class ReplaceCardExample {
    private volatile CardOrderRestApi api;

    public CardOrderRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("apiKey");
                    clientConfiguration.setSecretKey("secretKey");
                    clientConfiguration.setBaseUrl("https://api.thedecard.com");
                    api = new CardOrderRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Replace Card
     *
     * <p>Creates a replacement order for an existing card. The replacement can be due to various reasons
     * such as card damage, loss, or security concerns. The original card will be terminated and a new card will be issued.
     * Weight: 10
     *
     * @throws ApiException if the Api call fails
     */
    public void replaceCardExample() throws ApiException {
        ReplaceCardOrderRequest request = new ReplaceCardOrderRequest();
        request.setCardOrderRef("replacement_ref_789");
        request.setReplaceCardId("card_123456");

        ApiResponse<CardOrderResponse> response = getApi().replaceCard(request);
        System.out.println(response.getData());

    }
}
