/*
 * CardBridge Java Connector
 * OpenAPI Specifications for the CardBridge Card Order Management API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.card;

import com.dcscc.connector.client.card.api.CardOrderRestApi;
import com.dcscc.connector.client.card.model.CardOrderResponse;
import com.dcscc.connector.client.card.model.VirtualToPhysicalRequest;
import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;

/**
 * API examples for CardOrderApi
 */
public class VirtualToPhysicalExample {
    private volatile CardOrderRestApi api;

    public CardOrderRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("apiKey");
                    clientConfiguration.setSecretKey("secretKey");
                    clientConfiguration.setBaseUrl("https://api.thedecard.com");
                    api = new CardOrderRestApi(clientConfiguration);
                }
            }
        }
        return api;
    }

    /**
     * Virtual To Physical Card Conversion
     *
     * <p>Creates an order to convert an existing virtual card to a physical card.
     * The physical card will be manufactured and shipped to the provided address while the virtual card remains active
     * until the physical card is activated.
     * Weight: 10
     *
     * @throws ApiException if the Api call fails
     */
    public void virtualToPhysicalExample() throws ApiException {
        VirtualToPhysicalRequest request = new VirtualToPhysicalRequest();
        request.setCardOrderRef("virtual_to_physical_ref_123");
        request.setReplaceCardId("virtual_card_123456");

        VirtualToPhysicalRequest.VirtualToPhysicalInfo virtualToPhysicalInfo = new VirtualToPhysicalRequest.VirtualToPhysicalInfo();
        virtualToPhysicalInfo.setCountryCode("SG");
        virtualToPhysicalInfo.setState("Singapore City");
        virtualToPhysicalInfo.setCity("Singapore City");
        virtualToPhysicalInfo.setPostalCode("542317");
        virtualToPhysicalInfo.setAddress("307B Anchirvale road");
        virtualToPhysicalInfo.setAddress2("#01-200");
        virtualToPhysicalInfo.setAddress3("Anchirvale Place");
        virtualToPhysicalInfo.setAddress4("Anchirvale Place");
        virtualToPhysicalInfo.setAddress5("Anchirvale Place");
        virtualToPhysicalInfo.setEmbossingName("lee");
        virtualToPhysicalInfo.setCardLayoutCode("MGEBP");
        virtualToPhysicalInfo.setNeedShippingInfo(Boolean.FALSE);
        ApiResponse<CardOrderResponse> response = getApi().virtualToPhysical(request);
        System.out.println(response.getData());
    }
}
