/*
 * dcs Java Connector
 * 3DS Authentication REST API Examples
 *
 * The version of the dcs API: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.dcscc.connector.examples.threeds;

import com.dcscc.connector.client.authorisation.api.ThreeDSRestApi;
import com.dcscc.connector.client.authorisation.model.ThreeDSChallengeRequest;
import com.dcscc.connector.client.authorisation.model.ThreeDSChallengeResponse;
import com.dcscc.connector.client.common.ApiResponse;
import com.dcscc.connector.client.common.configuration.ClientConfiguration;
import com.dcscc.connector.client.common.exception.ApiException;

/**
 * API examples for 3DS Challenge Authentication
 */
public class AuthenticateExample {
    private volatile ThreeDSRestApi api;

    public ThreeDSRestApi getApi() {
        if (api == null) {
            synchronized (this) {
                if (api == null) {
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setApiKey("your-api-key");
                    clientConfiguration.setSecretKey("your-secret-key");
                    clientConfiguration.setBaseUrl("https://api.thedecard.com");
                    api = new ThreeDSRestApi(clientConfiguration);
                }
            }

        }
        return api;
    }

    /**
     * Process 3DS challenge authentication
     *
     * <p>Processes the result of a 3DS challenge authentication, updating the
     * authentication status based on the cardholder's response to the challenge.
     * The challenge can be approved or declined, and the system will update the
     * transaction status accordingly.
     * Weight: 5
     *
     * @throws ApiException if the Api call fails
     */
    public void authenticateExample() throws ApiException {
        ThreeDSChallengeRequest request = new ThreeDSChallengeRequest()
                .setChallengeId("CHALLENGE_123456789")
                .setApproveStatus("APPROVE"); // APPROVE or REJECT

        ApiResponse<ThreeDSChallengeResponse> response = getApi().authenticate(request);
        System.out.println(response.getData());
    }
}
